project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - s1_visualization.qmd
    - s2_inference_continuous.qmd
    - s3_missingness.qmd
    - s4_sensitivity_analyses.qmd
    - s5_inferences_binary.qmd
    - references.qmd

website:
  title: "Longitudinal Data Modeling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: s1_visualization.qmd
        text: Visualization
      - href: s2_inference_continuous.qmd
        text: Inference from Continuous Data
      - href: s3_missingness.qmd
        text: Missing Data Handling
      - href: s4_sensitivity_analyses.qmd
        text: Sensitivity Analyses
      - href: s5_inferences_binary.qmd
        text: Inference from Binary Data
      - href: https://alex-lauer.github.io/GMDS-Summer-School/
        text: Link to Solutions
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

