# Introduction

**Authors**

-   Dr. Marietta Kirchner, Institute of Medical Biometry, Heidelberg University

-   Dr. Alexandra Lauer, Boehringer Ingelheim Pharma GmbH & Co. KG

**Published**

```{r}
Sys.Date()
```

## Workshop Structure

This class focuses on the longitudinal modeling of data from Patient Reported Outcomes (PROs). It is meant to be hands-on class with applications in R.

Content and structure follow the book by [@mallinckrodt2016]. We would like to extend our warmest gratitude towards Dr. Mallinckrodt for providing the example data for the workshop.

The following topics will be covered:

-   Welcome and Introduction (WS session 1)

-   Exploration and visualization of longitudinal data (WS session 1/2)

-   Inferences from longitudinal data (WS session 3 + 4)

-   Assessment of missingness patterns (WS session 5)

-   Sensitivity analyses to assess the impact of missingness (WS session 6)

-   Annex: Inferences from longitudinal binary data (WS session 7)

## Longitudinal Data

This workshop focuses on the analysis of data observed in randomized clinical trials (RCTs). Here, patients have assessments taken at the start of their treatment and then subsequently throughout the course of the trial based on a pre-specified schedule of assessments. The measurement at the start of the treatment is usually referred to as the baseline.

Researchers can be interested in

1.  the occurrence of a certain event during the course of the trial, e.g. death or a cardiac event, or the time to the occurrence of such an event, or

2.  the longitudinal profile from multiple repeated measurements taken, with a focus on either estimates at a landmark visit or across several time points.

The outcomes under point 1 can be handled via a comparison of the percentages of patients with events between treatment arms, or a time-to-event analysis. Both are out of scope of this workshop.

## Basics about RStudio (pre-read)

If you are not used to working with R and RStudio so far, we recommend for you to familiarize yourself with the following useful content:

-   [RStudio User Guide](https://docs.posit.co/ide/user/)

-   [RStudio Cheatsheet](https://rstudio.github.io/cheatsheets/html/rstudio-ide.html)

-   The following two cheatsheets for [dplyr](https://rstudio.github.io/cheatsheets/html/data-transformation.html) (data wrangling) and [ggplot2](https://rstudio.github.io/cheatsheets/html/data-visualization.html) (plotting and visualizations)

-   This video about [Quarto](https://www.youtube.com/watch?v=_f3latmOhew)
